version: '3'

networks:
    nexus:
        external: true
      
volumes:
    kafka1-logs:
        driver: local
    kafka2-logs:
        driver: local
    kafka3-logs:
        driver: local

services:

    mysqldb:
        image: mysql:8
        command: [--character-set-server=latin1, --collation-server=latin1_swedish_ci]
        hostname: mysqldb
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=xdjob
            - MYSQL_USER=xd
            - MYSQL_PASSWORD=admin
        networks:
            - nexus
        ports:
            - "3306"
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.labels.nexus.ingest-admin == true
                    
    redis:
        image: redis:3
        hostname: redis
        networks:
            - nexus
        ports:
            - "6379"
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.labels.nexus.ingest-admin == true
                    
    xd-admin:
        image: nexusjpl/ingest-admin
        hostname: xd-admin
        depends_on:
            - "mysqldb"
            - "redis"
        networks:
            - nexus
        ports:
          - "9393:9393"
        environment:
            - MYSQL_PORT_3306_TCP_ADDR=mysqldb
            - MYSQL_PORT_3306_TCP_PORT=3306
            - MYSQL_USER=xd
            - MYSQL_PASSWORD=admin
            - REDIS_ADDR=redis
            - REDIS_PORT=6379
            - ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
            - ZOOKEEPER_XD_CHROOT=springxd
            - KAFKA_BROKERS=kafka1:9092,kafka2:9092,kafka3:9092
            - KAFKA_ZKADDRESS=zk1:2181,zk2:2181,zk3:2181/kafka
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.labels.nexus.ingest-admin == true
  
    xd-container:
        image: nexusjpl/ingest-container
        depends_on:
            - "xd-admin"
        networks:
            - nexus
        volumes:
            - /efs/data/share/datasets:/usr/local/data/nexus/
        environment:
            - MYSQL_PORT_3306_TCP_ADDR=mysqldb
            - MYSQL_PORT_3306_TCP_PORT=3306
            - MYSQL_USER=xd
            - MYSQL_PASSWORD=admin
            - REDIS_ADDR=redis
            - REDIS_PORT=6379
            - ZOOKEEPER_CONNECT=zk1:2181,zk2:2181,zk3:2181
            - ZOOKEEPER_XD_CHROOT=springxd
            - KAFKA_BROKERS=kafka1:9092,kafka2:9092,kafka3:9092
            - KAFKA_ZKADDRESS=zk1:2181,zk2:2181,zk3:2181/kafka
        deploy:
            mode: global
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
                window: 120s
            placement:
                constraints:
                    - node.labels.nexus.ingest == true

    zk1:
        image: zookeeper
        hostname: zk1
        networks:
            - nexus
        volumes:
            - /data/zk1/data:/data
            - /data/zk1/datalog:/datalog
        environment:
            - ZOO_MY_ID=1
            - "ZOO_SERVERS=server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888"
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.labels.nexus.ingest-msg == true
                    - node.labels.nexus.zoo.id == 1
    zk2:
        image: zookeeper
        hostname: zk2
        networks:
            - nexus
        volumes:
            - /data/zk2/data:/data
            - /data/zk2/datalog:/datalog
        environment:
            - ZOO_MY_ID=2
            - "ZOO_SERVERS=server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888"
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.labels.nexus.ingest-msg == true
                    - node.labels.nexus.zoo.id == 2
                    
    zk3:
        image: zookeeper
        hostname: zk3
        networks:
            - nexus
        volumes:
            - /data/zk3/data:/data
            - /data/zk3/datalog:/datalog
        environment:
            - ZOO_MY_ID=3
            - "ZOO_SERVERS=server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888"
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.labels.nexus.ingest-msg == true
                    - node.labels.nexus.zoo.id == 3
                    
    kafka1:
        image: nexusjpl/kafka
        command: ["/usr/local/kafka/current/config/kafka.properties", "--override", "zookeeper.connect=zk1:2181,zk2:2181,zk3:2181/kafka", "--override", "broker.id=1"]
        hostname: kafka1
        depends_on:
            - "zk1"
            - "zk2"
            - "zk3"
        networks:
            - nexus
        volumes:
            - kafka1-logs:/tmp/kafka-logs
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.labels.nexus.ingest-msg == true
                    - node.labels.nexus.kafka.id == 1
                    
    kafka2:
        image: nexusjpl/kafka
        command: ["/usr/local/kafka/current/config/kafka.properties", "--override", "zookeeper.connect=zk1:2181,zk2:2181,zk3:2181/kafka", "--override", "broker.id=2"]
        hostname: kafka2
        depends_on:
            - "zk1"
            - "zk2"
            - "zk3"
        networks:
            - nexus
        volumes:
            - kafka2-logs:/tmp/kafka-logs
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.labels.nexus.ingest-msg == true
                    - node.labels.nexus.kafka.id == 2
                    
    kafka3:
        image: nexusjpl/kafka
        command: ["/usr/local/kafka/current/config/kafka.properties", "--override", "zookeeper.connect=zk1:2181,zk2:2181,zk3:2181/kafka", "--override", "broker.id=3"]
        hostname: kafka3
        depends_on:
            - "zk1"
            - "zk2"
            - "zk3"
        networks:
            - nexus
        volumes:
            - kafka3-logs:/tmp/kafka-logs
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints:
                    - node.labels.nexus.ingest-msg == true
                    - node.labels.nexus.kafka.id == 3
        