version: '3'

networks:
  ingestadmin_ingestnetwork:
      external: true
  nexus:
      external: true

volumes:
  data-volume:

services:

    xd-container:
        image: nexusjpl/ingest-container:1
        container_name: xd-container
        command: [-c]
        environment:
            - MYSQL_PORT_3306_TCP_ADDR=mysqldb
            - MYSQL_PORT_3306_TCP_PORT=3306
            - MYSQL_USER=xd
            - MYSQL_PASSWORD
            - REDIS_ADDR=redis
            - REDIS_PORT=6379
            - "ZOOKEEPER_CONNECT=zkhost:2181"
            - ZOOKEEPER_XD_CHROOT=springxd
            - "KAFKA_BROKERS=kafka1:9092"
            - "KAFKA_ZKADDRESS=zkhost:2181/kafka"
        external_links:
            - mysqldb
            - redis
        extra_hosts:
            - "zkhost:$ZK_HOST_IP"
            - "kafka1:$KAFKA_HOST_IP"
        networks:
            - default
            - ingestadmin_ingestnetwork
            - nexus
        volumes:
              - data-volume:/usr/local/data/nexus
        deploy:
            placement:
                constraints:
                    - node.labels.nexus.type == ingest
